services:

  frontend:
    build: ./frontend

    container_name: cyvxai-frontend

    restart: always

    ports:
      - "3000:3000"

    depends_on:
      - backend

  backend:
    build: ./backend

    container_name: cyvxai-backend

    restart: always

    ports:
      - "8000:8000"

    env_file:
      - .env

  postgres:
    image: postgres:16

    container_name: cyvxai-postgres

    restart: always

    environment:
      POSTGRES_USER: cyvxai
      POSTGRES_PASSWORD: cyvxai
      POSTGRES_DB: cyvxai

  redis:
    image: redis:7

    container_name: cyvxai-redis

    restart: always

  nginx:
    image: nginx:latest

    container_name: cyvxai-nginx

    restart: always

    ports:
      - "80:80"

    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf:ro

    depends_on:
      - frontend
      - backend
