apiVersion: v1
kind: Service
metadata:
  name: cyvx-cluster
  namespace: {{ .Values.namespace }}
spec:
  clusterIP: None
  selector:
    app: cyvx-cluster
  ports:
    - name: http
      port: {{ .Values.service.clusterPort }}
      targetPort: {{ .Values.service.clusterPort }}
