apiVersion: apps/v1
kind: Deployment
metadata:
  name: leakos-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: python:3.10
          command: ["bash", "-c"]
          args:
            - pip install fastapi uvicorn pandas && uvicorn services.api.main:app --host 0.0.0.0 --port 8000
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: api
  ports:
    - port: 8000
      targetPort: 8000
  type: NodePort
