apiVersion: apps/v1
kind: Deployment

metadata:
  name: cyvxai

spec:
  replicas: 3

  selector:
    matchLabels:
      app: cyvxai

  template:
    metadata:
      labels:
        app: cyvxai

    spec:
      containers:
      - name: cyvxai
        image: cyvxai:latest

        ports:
        - containerPort: 8000
