"use strict";

function renderControlRoom(options = {}) {
  const localToken = options.localToken || "";
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<title>CYVX Autonomous Company Control Room</title>
<style>
:root{color-scheme:dark;--bg:#080a0f;--panel:#11151d;--panel2:#171d28;--line:#293244;--text:#f4f7fb;--muted:#9ba8bb;--good:#4ade80;--warn:#fbbf24;--bad:#fb7185;--brand:#8b5cf6;--brand2:#22d3ee}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at top,#15112a 0,#080a0f 42%);color:var(--text);font:15px/1.45 system-ui,-apple-system,Segoe UI,sans-serif}header{position:sticky;top:0;z-index:20;padding:14px 16px;border-bottom:1px solid var(--line);background:#080a0fe8;backdrop-filter:blur(16px)}h1{font-size:18px;margin:0}.sub{color:var(--muted);font-size:12px}.shell{max-width:1280px;margin:auto;padding:14px;display:grid;gap:14px}.grid{display:grid;gap:12px}.two{grid-template-columns:repeat(auto-fit,minmax(290px,1fr))}.card{background:linear-gradient(160deg,var(--panel),var(--panel2));border:1px solid var(--line);border-radius:16px;padding:14px;box-shadow:0 16px 50px #0005}.card h2,.card h3{margin:0 0 10px}.metric{font-size:27px;font-weight:800}.muted{color:var(--muted)}label{display:grid;gap:5px;margin:9px 0;color:var(--muted);font-size:12px}input,textarea,select,button{width:100%;border-radius:10px;border:1px solid var(--line);background:#090d14;color:var(--text);padding:11px;font:inherit}textarea{min-height:84px;resize:vertical}button{cursor:pointer;background:linear-gradient(100deg,var(--brand),#5b21b6);font-weight:750;border:0}button.secondary{background:#1b2432;border:1px solid var(--line)}button.good{background:#166534}.row{display:flex;gap:8px;align-items:center}.row>*{flex:1}.status-completed,.status-active,.status-ready{color:var(--good)}.status-failed{color:var(--bad)}.status-pending,.status-running{color:var(--warn)}.list{display:grid;gap:8px}.item{padding:10px;border:1px solid var(--line);border-radius:11px;background:#0c1119}.item strong{display:block}.toolbar{display:flex;gap:8px;flex-wrap:wrap}.toolbar button{width:auto;min-width:112px}.hidden{display:none!important}pre{white-space:pre-wrap;word-break:break-word;background:#070a0f;border:1px solid var(--line);padding:10px;border-radius:10px;max-height:320px;overflow:auto}.toast{position:fixed;right:14px;bottom:14px;max-width:360px;padding:12px 14px;border-radius:12px;background:#111827;border:1px solid var(--line);box-shadow:0 16px 60px #0009;z-index:99}.agent-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:8px}.agent{padding:10px;border-radius:12px;border:1px solid var(--line);background:#0b1018}.agent b{display:block}.progress{height:7px;background:#080b10;border-radius:99px;overflow:hidden;margin-top:8px}.progress i{display:block;height:100%;background:linear-gradient(90deg,var(--brand),var(--brand2))}@media(max-width:560px){.shell{padding:10px}.row{display:grid}.toolbar button{width:100%}}
</style>
</head>
<body>
<header><h1>CYVX Autonomous Company</h1><div class="sub">Idea → governed company → nine-agent execution → evidence → measurement → learning</div></header>
<main class="shell">
<section class="card"><h2>Control access</h2><div class="row"><label>Runtime token<input id="token" type="password" autocomplete="off" placeholder="Bearer token"></label><button id="saveToken">Connect</button></div><div class="sub">Production requires a strong server-side token. The browser stores it only in local storage.</div></section>
<section class="grid two">
<div class="card"><h2>Create company mission</h2><form id="createForm">
<label>Name<input name="name" required maxlength="120" value="CYVX Autonomous Revenue Company"></label>
<label>Description<textarea name="description" required>Build and operate an owned, measurable revenue capability with governed automation and durable evidence.</textarea></label>
<label>Target customer<input name="target_customer" required value="Service businesses that need a repeatable revenue operating system"></label>
<label>Offer<textarea name="offer" required>Install an evidence-backed operating system that turns qualified demand into collected and recurring revenue.</textarea></label>
<div class="row"><label>Price cents<input name="price_cents" type="number" min="0" value="150000"></label><label>Location<input name="location" value="United States"></label></div>
<label>Objective<textarea name="objective" required>Generate the first verified qualified lead and create the operating system required to convert it.</textarea></label>
<div class="row"><label>Target metric<input name="target_metric" value="lead_count"></label><label>Target value<input name="target_value" type="number" min="0" value="1"></label></div>
<button>Create governed runtime</button></form></div>
<div class="card"><h2>Portfolio</h2><div class="toolbar"><button class="secondary" id="refresh">Refresh</button></div><div id="companies" class="list"></div></div>
</section>
<section id="companyPanel" class="hidden grid">
<div class="card"><div class="row"><div><h2 id="companyName">Company</h2><div id="companyMeta" class="muted"></div></div><div class="toolbar"><button class="good" id="approve">Approve</button><button id="tick">Run tick</button><button id="run">Run to idle</button></div></div><div id="scoreboard" class="grid two" style="margin-top:12px"></div></div>
<div class="card"><h2>Nine-agent team</h2><div id="agents" class="agent-grid"></div></div>
<div class="grid two"><div class="card"><h2>Task ledger</h2><div id="tasks" class="list"></div></div><div class="card"><h2>Durable memory & learning</h2><div id="memories" class="list"></div></div></div>
<div class="grid two"><div class="card"><h2>Record measured outcome</h2><form id="outcomeForm"><div class="row"><label>Metric<input name="metric_name" required value="lead_count"></label><label>Value<input name="value" type="number" step="any" required value="0"></label><label>Unit<input name="unit" value="count"></label></div><label>Source<input name="source" required value="operator-verified"></label><label>Observed result<textarea name="observed_result" required></textarea></label><label>Learning<textarea name="learning" required></textarea></label><label>Next hypothesis<textarea name="next_hypothesis" required></textarea></label><button>Measure → learn → improve</button></form></div><div class="card"><h2>Outside-world integration</h2><form id="integrationForm"><label>Name<input name="name" required placeholder="crm-production"></label><label>HTTPS webhook URL<input name="url" required placeholder="https://..."></label><label>Secret environment variable<input name="secret_env" required placeholder="CYVX_CRM_WEBHOOK_SECRET"></label><label>Allowed event types<input name="allowed" required value="lead.qualified,outcome.recorded"></label><button>Register least-privilege integration</button></form><div id="integrations" class="list" style="margin-top:10px"></div></div></div>
<div class="card"><h2>Event stream</h2><pre id="events"></pre></div>
</section>
</main><div id="toast" class="toast hidden"></div>
<script>
const S={token:localStorage.getItem('cyvx_company_token')||${JSON.stringify(localToken)},companyId:null,graph:null};
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(message,error=false){const el=$('toast');el.textContent=message;el.style.borderColor=error?'var(--bad)':'var(--good)';el.classList.remove('hidden');setTimeout(()=>el.classList.add('hidden'),4200)}
async function api(path,options={}){const headers={'content-type':'application/json',...(options.headers||{})};if(S.token)headers.authorization='Bearer '+S.token;const r=await fetch(path,{...options,headers});let p={};try{p=await r.json()}catch{}if(!r.ok)throw new Error(p.error?.message||p.message||('HTTP '+r.status));return p}
function fd(form){const out={};for(const [k,v] of new FormData(form))out[k]=v;return out}
async function loadCompanies(){const p=await api('/api/v1/company-runtime/companies');const rows=p.companies||[];$('companies').innerHTML=rows.length?rows.map(function(x){return '<button class="secondary item" data-id="'+esc(x.company_id)+'"><strong>'+esc(x.name)+'</strong><span class="status-'+esc(x.status)+'">'+esc(x.status)+'</span> · '+Object.entries(x.task_counts||{}).map(function(e){return esc(e[0])+': '+e[1]}).join(' · ')+'</button>'}).join(''):'<div class="muted">No company runtimes yet.</div>';document.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>openCompany(b.dataset.id))}
async function openCompany(id){S.companyId=id;const p=await api('/api/v1/company-runtime/companies/'+encodeURIComponent(id));S.graph=p.company;render();$('companyPanel').classList.remove('hidden')}
function render(){const g=S.graph,o=g.operator,c=o.company,contract=o.contract;$('companyName').textContent=c.name;$('companyMeta').textContent=g.team.status+' · '+g.team.model_provider+' · mission '+o.mission.status;const counts={};g.tasks.forEach(t=>counts[t.status]=(counts[t.status]||0)+1);const completed=counts.completed||0;const total=g.tasks.length;const target=contract.target_metric+' '+contract.comparator+' '+contract.target_value;const cards=[['Outcome contract',target],['Agent work',completed+'/'+total],['Leads',c.counters?.leads_count||0],['Revenue','$'+((c.counters?.revenue_cents||0)/100).toFixed(2)]];$('scoreboard').innerHTML=cards.map(function(pair){const k=pair[0],v=pair[1];return '<div class="item"><span class="muted">'+esc(k)+'</span><div class="metric">'+esc(v)+'</div>'+(k==='Agent work'?'<div class="progress"><i style="width:'+(total?completed/total*100:0)+'%"></i></div>':'')+'</div>'}).join('');$('agents').innerHTML=g.agents.map(a=>'<div class="agent"><b>'+esc(a.label)+'</b><span class="status-'+esc(a.status)+'">'+esc(a.status)+'</span><div class="sub">done '+a.completed_tasks+' · failed '+a.failed_tasks+'</div></div>').join('');$('tasks').innerHTML=g.tasks.map(t=>'<div class="item"><strong>'+esc(t.role)+' · '+esc(t.kind)+'</strong><span class="status-'+esc(t.status)+'">'+esc(t.status)+'</span><div class="sub">priority '+t.priority+' · attempts '+t.attempts+'/'+t.max_attempts+'</div>'+(t.error?'<div class="status-failed">'+esc(t.error)+'</div>':'')+(t.artifact_sha256?'<div class="sub">proof '+esc(t.artifact_sha256.slice(0,16))+'…</div>':'')+'</div>').join('');const learningHtml=(g.learnings||[]).map(x=>'<div class="item"><strong>'+esc(x.metric_name)+'</strong>'+esc(x.learning)+'<div class="sub">Next: '+esc(x.next_hypothesis)+'</div></div>').join('');const memoryHtml=(g.memories||[]).slice(0,12).map(x=>'<div class="item"><strong>'+esc(x.role)+' · '+esc(x.kind)+'</strong><div class="sub">'+esc(x.content?.summary||JSON.stringify(x.content).slice(0,220))+'</div></div>').join('');$('memories').innerHTML=learningHtml||memoryHtml||'<div class="muted">No durable memory yet.</div>';$('integrations').innerHTML=(g.integrations||[]).map(x=>'<div class="item"><strong>'+esc(x.name)+'</strong>'+esc(x.url)+'<div class="sub">'+esc(x.allowed_event_types.join(', '))+' · secret '+esc(x.secret_env)+'</div></div>').join('')||'<div class="muted">No external integrations registered.</div>';$('events').textContent=(g.events||[]).slice(0,40).map(e=>e.created_at+' '+e.type+' '+JSON.stringify(e.payload)).join('\n')}
$('saveToken').onclick=async()=>{S.token=$('token').value.trim();localStorage.setItem('cyvx_company_token',S.token);try{await loadCompanies();toast('Connected')}catch(e){toast(e.message,true)}};$('token').value=S.token;$('refresh').onclick=()=>loadCompanies().catch(e=>toast(e.message,true));
$('createForm').onsubmit=async e=>{e.preventDefault();const x=fd(e.target);const body={name:x.name,description:x.description,target_customer:x.target_customer,offer:x.offer,price_cents:Number(x.price_cents),location:x.location,keywords:[],outcome_contract:{objective:x.objective,target_metric:x.target_metric,comparator:'>=',target_value:Number(x.target_value),target_unit:'count',max_budget_cents:0,approval_threshold_cents:0,risk_level:'medium'}};try{const p=await api('/api/v1/company-runtime/companies',{method:'POST',body:JSON.stringify(body)});toast('Company runtime created');await loadCompanies();await openCompany(p.company.team.company_id)}catch(err){toast(err.message,true)}};
$('approve').onclick=async()=>{try{await api('/api/v1/company-runtime/companies/'+S.companyId+'/approve',{method:'POST',body:JSON.stringify({decision_reason:'Approved in CYVX control room'})});await openCompany(S.companyId);toast('Approved and scheduled')}catch(e){toast(e.message,true)}};$('tick').onclick=async()=>{try{const p=await api('/api/v1/company-runtime/companies/'+S.companyId+'/tick',{method:'POST',body:'{}'});toast(p.tick.summary||p.tick.status);await openCompany(S.companyId)}catch(e){toast(e.message,true)}};$('run').onclick=async()=>{try{toast('Running governed work…');await api('/api/v1/company-runtime/companies/'+S.companyId+'/run',{method:'POST',body:JSON.stringify({maximum_ticks:100})});await openCompany(S.companyId);toast('Runtime reached idle or a governed block')}catch(e){toast(e.message,true)}};
$('outcomeForm').onsubmit=async e=>{e.preventDefault();const x=fd(e.target);try{await api('/api/v1/company-runtime/companies/'+S.companyId+'/outcomes',{method:'POST',body:JSON.stringify({...x,value:Number(x.value)})});await openCompany(S.companyId);toast('Outcome recorded; improvement task queued')}catch(err){toast(err.message,true)}};$('integrationForm').onsubmit=async e=>{e.preventDefault();const x=fd(e.target);try{await api('/api/v1/company-runtime/companies/'+S.companyId+'/integrations',{method:'POST',body:JSON.stringify({name:x.name,kind:'webhook',url:x.url,secret_env:x.secret_env,allowed_event_types:x.allowed.split(',').map(v=>v.trim()).filter(Boolean)})});await openCompany(S.companyId);toast('Integration registered')}catch(err){toast(err.message,true)}};
if(S.token)loadCompanies().catch(()=>{});
</script></body></html>`;
}

module.exports = { renderControlRoom };
